apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: todo-evolution
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: todo-evolution
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi